number: '0123456789०१२३४५६७८९'
symbol: '!"#$%&''()*+,-/:;<=>?@[\\]^_`{|}~ ।॰'
lang_char: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.ँंःअअंअःआइईउऊऋएऐऑओऔकखगघङचछजझञटठडढणतथदधनऩपफबभमयरऱलळवशषसह़ािीुूृॅेैॉोौ्ॐ॒क़ख़ग़ज़ड़ढ़फ़ॠ'
experiment_name: 'ne_finetuned'
train_data: 'all_data/train/names'
valid_data: 'all_data/val/names'
manualSeed: 1111
workers: 4
batch_size: 25 #25
num_iter: 300
valInterval: 20
saved_model: 'saved_models' #'saved_models/ne_filtered/iter_300000.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.001
grad_clip: 5
#Data processing
select_data: 'names' # this is dataset folder in train_data
batch_ratio: '1'
total_data_usage_ratio: 1.0
batch_max_length: 34
imgH: 32
imgW: 100
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 512
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
