seed: 1111
experiment_name: phase1
train_data: /kaggle/working/training_and_validation_set/training
val_data: /kaggle/working/training_and_validation_set/validation
select_data: select_data
batch_ratio: "1"
total_data_usage_ratio: 1
train_images: 10_000
val_images: 700
eval_images: 300
img_height: 64
img_width: 600
PAD: True
contrast_adjust: 0
character: 0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.ँंःअअंअःआइईउऊऋएऐऑओऔकखगघङचछजझञटठडढणतथदधनऩपफबभमयरऱलळवशषसह़ािीुूृॅेैॉोौ्ॐ॒क़ख़ग़ज़ड़ढ़फ़ॠ।०१२३४५६७८९॰
sensitive: True
batch_max_length: 34
data_filtering_off: False
workers: 2
batch_size: 8
n_iter: 10_000
val_period: 1_000
show_number: 8
continue_from: devanagari.pth
strict: True
adam: False
lr: 1.
rho: 0.95
eps: 0.00000001
grad_clip: 5
Transformation: None
FeatureExtraction: ResNet
SequenceModeling: BiLSTM
Prediction: CTC
freeze_FeatureFxtraction: False
rgb: False
input_channel: 1
output_channel: 512
freeze_SequenceModeling: False
hidden_size: 512
new_prediction: False
decode: greedy
